export const DEFAULT_CATEGORIES = [
  "Fruits & Vegetables",
  "Dairy & Eggs",
  "Meat & Seafood",
  "Pantry Staples",
  "Beverages",
  "Snacks",
  "Frozen Foods",
  "Bakery",
  "Other"
];

export const DEFAULT_ITEMS = [
  { name: "Milk", category: "Dairy & Eggs", priority: "high" as const },
  { name: "Bread", category: "Bakery", priority: "high" as const },
  { name: "Eggs", category: "Dairy & Eggs", priority: "high" as const },
  { name: "Bananas", category: "Fruits & Vegetables", priority: "medium" as const },
  { name: "Chicken", category: "Meat & Seafood", priority: "medium" as const },
  { name: "Rice", category: "Pantry Staples", priority: "low" as const },
  { name: "Tomatoes", category: "Fruits & Vegetables", priority: "medium" as const },
  { name: "Onions", category: "Fruits & Vegetables", priority: "medium" as const },
  { name: "Potatoes", category: "Fruits & Vegetables", priority: "low" as const },
  { name: "Cheese", category: "Dairy & Eggs", priority: "medium" as const },
  { name: "Fish", category: "Meat & Seafood", priority: "medium" as const },
  { name: "Avocado", category: "Fruits & Vegetables", priority: "medium" as const },
  { name: "Garlic", category: "Fruits & Vegetables", priority: "low" as const },
  { name: "Ginger", category: "Fruits & Vegetables", priority: "low" as const },
  { name: "Curds", category: "Dairy & Eggs", priority: "medium" as const },
  { name: "Coriander Leaves", category: "Fruits & Vegetables", priority: "medium" as const },
  { name: "Coconut", category: "Fruits & Vegetables", priority: "low" as const },
  { name: "Salt", category: "Pantry Staples", priority: "low" as const },
  { name: "Tea", category: "Beverages", priority: "high" as const },
  { name: "Curry Leaves", category: "Fruits & Vegetables", priority: "low" as const },
  { name: "Capsicum", category: "Fruits & Vegetables", priority: "medium" as const },
  { name: "Fruits", category: "Fruits & Vegetables", priority: "medium" as const },
  { name: "Noodles", category: "Pantry Staples", priority: "medium" as const },
  { name: "Pasta", category: "Pantry Staples", priority: "medium" as const },
  { name: "Chillies", category: "Fruits & Vegetables", priority: "low" as const },
];

